Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2022-05, with the labels that each got.

#37 Add context and logger to MachineProvider interface funcs
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/updates_test.go
  pkg/machineproviders/mock/zz_generated_machine_provider_mock.go
  pkg/machineproviders/types.go
Labels: approved, lgtm, size/L

#26 [OCPCLOUD-1441] Add operator manifests
  manifests/0000_31_control-plane-machine-set-operator_00_controlplanemachineset.crd.yaml
  manifests/0000_31_control-plane-machine-set-operator_01_rbac.yaml
  manifests/0000_31_control-plane-machine-set-operator_02_service.yaml
  manifests/0000_31_control-plane-machine-set-operator_03_deployment.yaml
  manifests/0000_31_control-plane-machine-set-operator_04_clusteroperator.yaml
Labels: approved, lgtm, size/L

#40 [OCPCLOUD-1558] Extend provider config abstraction to be platform agnostic
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
Labels: approved, lgtm, size/L

#41 Ensure Cluster ID label is set on Machine template
  pkg/webhooks/controlplanemachineset/webhooks_test.go
Labels: approved, lgtm, size/S

#39 [OCPCLOUD-1543] Failure domain mapping
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
Labels: approved, lgtm, size/XXL

#43 Ensure master role and type label are present on OpenShift Machine Templates
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
Labels: approved, lgtm, size/M

#44 [OCPCLOUD-1565] Ensure invalid cluster state prevents further reconciliation
  pkg/controllers/controlplanemachineset/consts.go
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/controllers/controlplanemachineset/status.go
  pkg/controllers/controlplanemachineset/status_test.go
  pkg/controllers/controlplanemachineset/updates.go
  pkg/controllers/controlplanemachineset/updates_test.go
  pkg/test/resourcebuilder/node.go
Labels: approved, lgtm, size/XXL

#42 [OCPCLOUD-1544] Add OpenShift MachineProvider interface implementation tests
  go.mod
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
  pkg/test/resourcebuilder/aws_provider_spec.go
  pkg/test/resourcebuilder/machine.go
  pkg/test/resourcebuilder/machine_info.go
  pkg/test/resourcebuilder/metadata.go
  pkg/test/resourcebuilder/openshift_machine_v1beta1_template.go
Labels: approved, lgtm, size/XXL
