Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2022-09, with the labels that each got.

#93 Ensure machines that were previously ready are still considered ready
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
Labels: approved, lgtm, size/L

#91 Add OnDelete update functionality
  pkg/controllers/controlplanemachineset/updates.go
  pkg/controllers/controlplanemachineset/updates_test.go
Labels: approved, lgtm, size/L

#94 Enable pending tests for isControlPlaneMachineSetDegraded
  pkg/controllers/controlplanemachineset/controller_test.go
Labels: approved, lgtm, size/XS

#92 [OCPCLOUD-1570] Add initial end user documentation
  README.md
  docs/user/README.md
  docs/user/installation.md
  docs/user/update-strategies.md
Labels: approved, lgtm, size/XL

#96 Control Plane Machine Set manifest generator tweaks
  Makefile
  pkg/cmd/generate/generator.go
Labels: approved, lgtm, size/XS

#98 OCPBUGS-996: Add logic to handle extra updated machines in a single index + minor fixes
  pkg/controllers/controlplanemachineset/consts.go
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/controllers/controlplanemachineset/updates.go
  pkg/controllers/controlplanemachineset/updates_test.go
  pkg/test/resourcebuilder/machine_info.go
Labels: approved, lgtm, bugzilla/valid-bug, size/L, jira/severity-low, jira/valid-bug

#100 [OCPCLOUD-1570] Add more user documentation about failure domains and FAQs
  docs/user/README.md
  docs/user/failure-domains.md
Labels: approved, lgtm, size/L

#101 OCPBUGS-996: Reverts "Add logic to handle extra updated machines in a single index + minor fixes"
  pkg/controllers/controlplanemachineset/consts.go
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/controllers/controlplanemachineset/updates.go
  pkg/controllers/controlplanemachineset/updates_test.go
  pkg/test/resourcebuilder/machine_info.go
Labels: approved, lgtm, bugzilla/valid-bug, size/L, jira/severity-low, jira/valid-bug

#97 [OCPCLOUD-1678] Migrate validations to use CEL
  Makefile
  go.mod
  go.sum
  manifests/0000_31_control-plane-machine-set-operator_00_controlplanemachineset.crd.yaml
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain_test.go
  pkg/test/resourcebuilder/openstack_failure_domains.go
  pkg/webhooks/controlplanemachineset/suite_test.go
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_marketplace-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_console.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagecontentpolicy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagedigestmirrorset.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagetagmirrorset.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_node.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_project.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1alpha1/0000_10_config-operator_01_insightsdatagather.crd.yaml
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/Makefile
  vendor/github.com/openshift/api/machine/v1/control-plane-machine-set.aws.stable.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/control-plane-machine-set.azure.stable.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/control-plane-machine-set.gcp.stable.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/control-plane-machine-set.stable.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/types_aws.go
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machinehealthcheck.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#103 Ensure that an inactive CPMS does not cause changes to the cluster
  go.mod
  go.sum
  manifests/0000_31_control-plane-machine-set-operator_00_controlplanemachineset.crd.yaml
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/test/resourcebuilder/control_plane_machine_set.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/control-plane-machine-set.aws.stable.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/control-plane-machine-set.stable.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
