Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2022-06, with the labels that each got.

#48 Bug 2098508: Resolve panics and fix webhooks and logs and watches
  cmd/control-plane-machine-set-operator/main.go
  go.mod
  manifests/0000_31_control-plane-machine-set-operator_01_rbac.yaml
  manifests/0000_31_control-plane-machine-set-operator_03_deployment.yaml
  manifests/0000_31_control-plane-machine-set-operator_05_service.yaml
  manifests/0000_31_control-plane-machine-set-operator_06_webhook.yaml
  pkg/controllers/controlplanemachineset/cluster_operator.go
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
  vendor/k8s.io/klog/v2/klogr/README.md
  vendor/k8s.io/klog/v2/klogr/klogr.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, lgtm, bugzilla/valid-bug, size/M

#47 Provider abstrations
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/aws.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/aws_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
  pkg/test/resourcebuilder/aws_provider_spec.go
  pkg/test/resourcebuilder/azure_failure_domains.go
  pkg/test/resourcebuilder/azure_privder_spec.go
  pkg/test/resourcebuilder/gcp_failure_domains.go
  pkg/test/resourcebuilder/gcp_provider_spec.go
  pkg/test/resourcebuilder/openstack_failure_domains.go
  pkg/webhooks/controlplanemachineset/webhooks.go
Labels: approved, lgtm, size/XXL

#51 Refactor table tests to use cpmsBuilder, stick to camelCase log key convention
  docs/contributing.md
  pkg/controllers/controlplanemachineset/cluster_operator_test.go
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/controllers/controlplanemachineset/status_test.go
  pkg/controllers/controlplanemachineset/updates_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
  pkg/test/resourcebuilder/consts.go
  pkg/test/resourcebuilder/control_plane_machine_set.go
Labels: approved, lgtm, size/L
