Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2022-04, with the labels that each got.

#27 Update ControlPlaneMachineSet CRD
  Makefile
  go.mod
  go.sum
  hack/crds-sync.sh
  manifests/0000_31_controlplanemachineset.crd.yaml
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagedigestmirrorset.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagetagmirrorset.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_node.crd.yaml
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image_digest_mirror_set.go
  vendor/github.com/openshift/api/config/v1/types_image_tag_mirror_set.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_vsphereprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/golang.org/x/net/http2/errors.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/buffer/buffer.go
  vendor/k8s.io/klog/v2/internal/clock/README.md
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/internal/severity/severity.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/modules.txt
Labels: approved, lgtm

#24 [OCPCLOUD-1496] Add tests for updating status of ControlPlaneMachineSet
  pkg/controllers/controlplanemachineset/status.go
  pkg/controllers/controlplanemachineset/status_test.go
Labels: approved, lgtm

#28 [OCPCLOUD-1492] Implement watch filters
  cmd/control-plane-machine-set-operator/main.go
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/watch_filters.go
  pkg/controllers/controlplanemachineset/watch_filters_test.go
Labels: approved, lgtm

#31 Add generated files configuration
  .generated_files
Labels: approved, lgtm

#35 [OCPCLOUD-1496] Implement status reconciliation from MachineInfo
  pkg/controllers/controlplanemachineset/status.go
  pkg/controllers/controlplanemachineset/status_test.go
Labels: approved, lgtm, size/M

#34 [OCPCLOUD-1498] Implement supporting functions for reconcileMachineUpdates
  pkg/controllers/controlplanemachineset/updates.go
  pkg/controllers/controlplanemachineset/updates_test.go
Labels: approved, lgtm

#32 Logger keys should use lower camel case by convention
  Makefile
  docs/contributing.md
  hack/verify-log-keys.sh
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/controllers/controlplanemachineset/status.go
  pkg/controllers/controlplanemachineset/status_test.go
  pkg/controllers/controlplanemachineset/updates_test.go
Labels: approved, lgtm, size/L

#29 [OCPCLOUD-1523] Ensure missing indexes are included when sorting MachineInfos within updates
  pkg/controllers/controlplanemachineset/updates.go
  pkg/controllers/controlplanemachineset/updates_test.go
  pkg/machineproviders/types.go
  pkg/test/resourcebuilder/control_plane_machine_set.go
Labels: approved, lgtm, size/L

#36 Ensure log key regex handles single line declarations
  hack/verify-log-keys.sh
Labels: approved, lgtm, size/XS

#30 [OCPCLOUD-1525] Add AWS Failure Domain and Provider Config skeletons
  .golangci.yaml
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/suite_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/aws.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/aws_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/suite_test.go
  pkg/test/resourcebuilder/aws_provider_spec.go
Labels: approved, lgtm, size/XL
