Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2022-11, with the labels that each got.

#128 [OCPCLOUD-1765] Azure: Generate ControlPlaneMachineSet for clusters t…
  docs/user/README.md
  pkg/controllers/controlplanemachinesetgenerator/azure.go
  pkg/controllers/controlplanemachinesetgenerator/controller.go
  pkg/controllers/controlplanemachinesetgenerator/controller_test.go
  pkg/controllers/controlplanemachinesetgenerator/utils_test.go
  pkg/test/resourcebuilder/infrastructure.go
Labels: approved, lgtm, size/XXL

#130 OCPBUGS-3320: Deduplicate Failure Domains for the CPMS
  pkg/machineproviders/providers/machineproviders_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/set.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/set_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, size/L, jira/valid-bug

#131 Add support for Azure e2e tests
  test/e2e/common/common.go
  test/e2e/framework/framework.go
  test/e2e/framework/framework_test.go
Labels: size/L

#132 [OCPCLOUD-1776]: Enable CPMS for GCP
  pkg/test/resourcebuilder/gcp_provider_spec.go
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
Labels: approved, lgtm, size/L

#135 [OCPCLOUD-1781]: Ensure CPMS tests work on GCP
  test/e2e/framework/framework.go
  test/e2e/framework/framework_test.go
Labels: approved, lgtm, size/L

#137 [OCPCLOUD-1748] Check OnDelete strategy updates status
  test/e2e/common/common.go
  test/e2e/presubmit/presubmit.go
  test/e2e/presubmit_test.go
Labels: approved, lgtm, size/L

#138 OCPCLOUD-1741: e2e presubmit tests: ControlPlaneMachineSet uninstall
  test/e2e/common/common.go
  test/e2e/common/machine.go
  test/e2e/presubmit/presubmit.go
  test/e2e/presubmit_test.go
Labels: approved, lgtm, size/L

#141 OCPCLOUD-1742: e2e presubmit tests: generated ControlPlaneMachineSet replicas updated
  test/e2e/presubmit/presubmit.go
  test/e2e/presubmit_test.go
Labels: approved, lgtm, size/S

#142 Ensure stable output from RunCheckUntil
  test/e2e/framework/utils.go
  test/e2e/framework/utils_test.go
Labels: approved, lgtm, size/XS

#139 [OCPCLOUD-1749] Check on delete strategy correctly replaces machines
  test/e2e/common/machine.go
  test/e2e/common/rollingupdate.go
  test/e2e/periodic/periodic.go
  test/e2e/presubmit/presubmit.go
  test/e2e/presubmit_test.go
Labels: approved, lgtm, size/L

#144 Increase unit test timeout to 10m
  hack/test.sh
Labels: approved, lgtm, size/XS

#143 OCPCLOUD-1746: e2e presubmit test: activating ControlPlaneMachineSet doesn't cause rollout
  test/e2e/presubmit/presubmit.go
  test/e2e/presubmit_test.go
Labels: approved, lgtm, size/M

#140 [OCPCLOUD-1751] Add integration test for fulling rolling update replacement
  go.mod
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/controllers/controlplanemachineset/suite_test.go
  test/e2e/common_test.go
  test/e2e/framework/framework.go
  test/e2e/framework/utils.go
  test/e2e/helpers/cases.go
  test/e2e/helpers/clusteroperators.go
  test/e2e/helpers/controlplanemachineset.go
  test/e2e/helpers/formatters.go
  test/e2e/helpers/machine.go
  test/e2e/helpers/machine_test.go
  test/e2e/helpers/rollingupdate.go
  test/e2e/helpers/suite_test.go
  test/e2e/periodic/periodic.go
  test/e2e/periodic_test.go
  test/e2e/presubmit_test.go
  test/integration/machine_manager.go
Labels: approved, lgtm, size/XL

#145 OCPCLOUD-1750: e2e presubmit test: activating ControlPlaneMachineSet adds owner references
  test/e2e/helpers/cases.go
  test/e2e/helpers/machine.go
  test/e2e/presubmit_test.go
Labels: approved, lgtm, size/M
