Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2022-12, with the labels that each got.

#147 OCPCLOUD-1744: e2e presubmit: update to newest machine triggers inactive ControlPlaneMachineSet regeneration
  pkg/controllers/controlplanemachineset/controller_test.go
  test/e2e/framework/framework.go
  test/e2e/helpers/cases.go
  test/e2e/helpers/controlplanemachineset.go
  test/e2e/helpers/machine.go
  test/e2e/periodic_test.go
  test/e2e/presubmit_test.go
Labels: approved, lgtm, size/L

#148 OCPCLOUD-1798: e2e test: remove common test, unnecessary presubmit aftereach
  test/e2e/common_test.go
  test/e2e/presubmit_test.go
Labels: approved, lgtm, size/M

#149 OCPBUGS-4297: Fix stale cache issue on createMachine
  cmd/control-plane-machine-set-operator/main.go
  pkg/controllers/controlplanemachineset/cluster_operator_test.go
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/controllers/controlplanemachineset/status_test.go
  pkg/controllers/controlplanemachineset/updates.go
  pkg/controllers/controlplanemachineset/updates_test.go
  pkg/machineproviders/mock/zz_generated_machine_provider_mock.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/types.go
Labels: approved, lgtm, bugzilla/valid-bug, size/L, jira/severity-moderate, jira/valid-bug

#152 OCPCLOUD-1752: integration: rollingUpdate: test replaces a not needing update, deleted Machine
  pkg/controllers/controlplanemachineset/controller_test.go
Labels: approved, lgtm, size/S

#153 OCPCLOUD-1753: integration: rollingUpdate: test rebalances machines across failure domains
  pkg/controllers/controlplanemachineset/controller_test.go
Labels: approved, lgtm, size/L

#154 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/S

#155 Add testing strategy documentation
  docs/developer/test-strategy.md
Labels: approved, lgtm, size/L
