Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2022-08, with the labels that each got.

#71 Add missing "spec" in error path
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
Labels: approved, lgtm, size/XS

#58 [OCPCLOUD-1617] Implement OpenShift Machine Provider Interface for CPMS
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
  pkg/machineproviders/types.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#72 [OCPCLOUD-1490] Make sure finalizer RBAC is included for ControlPlaneMachineSet resources
  manifests/0000_31_control-plane-machine-set-operator_01_rbac.yaml
Labels: approved, lgtm, size/XS

#73 Ensure additional failure domains do not prevent installation of a ControlPlaneMachineSet
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
Labels: approved, lgtm, size/L

#76 Add OpenShift standard leader election configuration to manager
  cmd/control-plane-machine-set-operator/main.go
  go.mod
  go.sum
  manifests/0000_31_control-plane-machine-set-operator_01_rbac.yaml
  manifests/0000_31_control-plane-machine-set-operator_03_deployment.yaml
  pkg/util/leaderelection.go
  vendor/github.com/openshift/client-go/LICENSE
  vendor/github.com/openshift/client-go/config/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/authentication.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/clusteroperator.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/clusterversion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/console.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/image.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/imagecontentpolicy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/infrastructure.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/ingress.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/network.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/oauth.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/project.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/scheduler.go
  vendor/github.com/openshift/library-go/pkg/config/clusterstatus/clusterstatus.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/k8s.io/component-base/config/options/leaderelectionconfig.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#79 Bug 2115638: Ensure that the failure domain mapping is respected in getMachineInfo
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
Labels: approved, lgtm, bugzilla/valid-bug, size/L, bugzilla/severity-medium

#75 Test CPMS degraded when failing to create new Machines
  pkg/controllers/controlplanemachineset/consts.go
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
Labels: approved, lgtm, size/M

#77 Add image-references
  manifests/0000_31_control-plane-machine-set-operator_03_deployment.yaml
  manifests/image-references
Labels: approved, lgtm, size/S

#81 Add .ci-operator.yaml file
  .ci-operator.yaml
Labels: approved, lgtm, size/XS

#78 [OCPCLOUD-1650] Ensure we replace deleted machines in the RollingUpdate strategy
  pkg/controllers/controlplanemachineset/updates.go
  pkg/controllers/controlplanemachineset/updates_test.go
Labels: approved, lgtm, size/L

#80 Add manifests in the resulting docker image
  Dockerfile
  cmd/control-plane-machine-set-operator/main.go
  pkg/controllers/controlplanemachineset/cluster_operator.go
  pkg/controllers/controlplanemachineset/controller.go
Labels: approved, lgtm, size/M

#82 Bug 2115358: Fix panic when injecting nil FailureDomain
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
Labels: approved, bugzilla/severity-high, lgtm, bugzilla/valid-bug, size/M

#83 Bug 2115358: Ensure machine provider info can be gathered in a single failure domain
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
Labels: approved, bugzilla/severity-high, lgtm, bugzilla/valid-bug, size/L

#86 [OCPCLOUD-1647] Implement pre-flight Cluster state validation
  pkg/controllers/controlplanemachineset/consts.go
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
Labels: approved, lgtm, size/L

#85 [OCPCLOUD-1657] Add initial readme to repository root
  README.md
Labels: approved, lgtm, size/L

#84 Bug 2117439: Add webhook validation to prevent scenarios which can create known broken clusters
  pkg/test/resourcebuilder/azure_failure_domains.go
  pkg/test/resourcebuilder/azure_provider_spec.go
  pkg/test/resourcebuilder/gcp_failure_domains.go
  pkg/test/resourcebuilder/openstack_failure_domains.go
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
Labels: approved, bugzilla/severity-high, lgtm, bugzilla/valid-bug, qe-approved, size/L

#87 add more options for running tests
  Makefile
  README.md
  hack/test.sh
Labels: approved, lgtm, size/S

#89 Bug 2115358: Ensure a MachineProvider with no failure domains can create machines
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
Labels: approved, bugzilla/severity-high, lgtm, bugzilla/valid-bug, qe-approved, size/M

#90 Fix behavior in cluster state validation and machine info generation
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
Labels: approved, lgtm, size/S
