Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2022-10, with the labels that each got.

#106 OCPBUGS-1348: Fix deleting machine affecting new machine failure domain
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
Labels: approved, lgtm, bugzilla/valid-bug, size/M, jira/valid-bug

#107 Add Make target for building and pushing images
  Makefile
Labels: approved, lgtm, size/S

#110 OCPBUGS-1645: Ensure the ControlPlaneMachineSet can handle machines that are not indexed from 0
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
Labels: approved, lgtm, bugzilla/valid-bug, size/XL, jira/valid-bug

#109 Updating ose-cluster-control-plane-machine-set-operator images to be consistent with ART
  .ci-operator.yaml
  Dockerfile
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/status.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
  pkg/test/conditions.go
  pkg/test/resourcebuilder/azure_failure_domains.go
  pkg/test/resourcebuilder/gcp_failure_domains.go
Labels: approved, lgtm, size/M

#111 OCPCLOUD-1675: Add support for generic platforms without failure domains
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/generic_platform.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
  pkg/test/resourcebuilder/vsphere_provider_spec.go
Labels: approved, lgtm, size/L

#113 OCPBUGS-1348: Fix machine not being marked as deleting
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
Labels: approved, lgtm, size/S, bugzilla/valid-bug, qe-approved, jira/valid-bug

#114 Update watches to include unowned control plane machines
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/watch_filters.go
  pkg/controllers/controlplanemachineset/watch_filters_test.go
Labels: approved, lgtm, size/M

#115 Add the ability to disable webhook registration
  cmd/control-plane-machine-set-operator/main.go
Labels: approved, lgtm, size/S

#117 Update log messages to use structured logs
  pkg/controllers/controlplanemachineset/watch_filters.go
Labels: approved, lgtm, size/S

#119 Update test timeout to 5 minutes
  hack/test.sh
Labels: approved, lgtm, size/XS

#118 OCPBUGS-2340: Ensure OnDelete strategy can handle non-standard indexes
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/controllers/controlplanemachineset/updates.go
  pkg/controllers/controlplanemachineset/updates_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, size/XL, jira/severity-moderate, jira/valid-bug

#120 OCPBUGS-2469: Don't set a name in related objects
  manifests/0000_31_control-plane-machine-set-operator_04_clusteroperator.yaml
Labels: approved, lgtm, bugzilla/valid-bug, size/XS, jira/valid-bug

#116 OCPBUGS-2446: Expose an error condition if an error is repeated more than 15 times in a row
  pkg/controllers/controlplanemachineset/cluster_operator.go
  pkg/controllers/controlplanemachineset/consts.go
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/status.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, size/L, jira/valid-bug

#121 Remove cpmsctl
  Makefile
  cmd/cpmsctl/main.go
  go.mod
  go.sum
  pkg/cmd/generate/generator.go
  pkg/cmd/generate/utils.go
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1alpha1/gatherconfig.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1alpha1/insightsdatagather.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1alpha1/insightsdatagatherspec.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1alpha1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1alpha1/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1alpha1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1alpha1/insightsdatagather.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1/controlplanemachineset.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1/doc.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1/machine_client.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/doc.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/generated_expansion.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/machine.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/machine_client.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/machinehealthcheck.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/machineset.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#122 Unpend remaining MachineProvider tests
  pkg/machineproviders/providers/machineproviders_test.go
Labels: approved, lgtm, size/L

#124 OCPBUGS-2741: Deduplicate failure domains when generating a ControlPlaneMachineSet
  pkg/controllers/controlplanemachinesetgenerator/controller_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/set.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/set_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
  pkg/webhooks/controlplanemachineset/webhooks.go
Labels: approved, lgtm, bugzilla/valid-bug, size/L, jira/severity-moderate, jira/valid-bug

#125 OCPBUGS-2854: Ensure generated CPMS includes any failure domain already present in control plane machines
  pkg/controllers/controlplanemachinesetgenerator/aws.go
  pkg/controllers/controlplanemachinesetgenerator/controller_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/set.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/set_test.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, size/L, jira/valid-bug

#123 OCPCLOUD-1674: Update installation docs to account for generation/activation
  docs/user/README.md
  docs/user/installation.md
Labels: approved, lgtm, size/L

#126 [OCPCLOUD-1735] Set up basic E2E test framework
  .golangci.yaml
  Makefile
  hack/e2e.sh
  hack/test.sh
  test/e2e/common/common.go
  test/e2e/common_test.go
  test/e2e/framework/framework.go
  test/e2e/framework/utils.go
  test/e2e/periodic_test.go
  test/e2e/presubmit_test.go
  test/e2e/suite_test.go
Labels: approved, lgtm, size/L
