Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2022-07, with the labels that each got.

#50 Require Machine role and type to be master
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
Labels: approved, lgtm, size/M

#52 [OCPCLOUD-1587] Validate discriminated unions via webhooks
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
Labels: approved, lgtm, size/XL

#54 [OCPCLOUD-1586] Update ControlPlaneMachineSet API from openshift/api
  go.mod
  go.sum
  hack/crds-sync.sh
  manifests/0000_31_control-plane-machine-set-operator_00_controlplanemachineset.crd.yaml
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/controllers/controlplanemachineset/status_test.go
  pkg/controllers/controlplanemachineset/updates_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain_test.go
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
  vendor/github.com/openshift/api/config/v1/0000_03_marketplace-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagedigestmirrorset.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagetagmirrorset.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_node.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/0000_10_awsplacementgroup.crd.yaml
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/register.go
  vendor/github.com/openshift/api/machine/v1/types.go
  vendor/github.com/openshift/api/machine/v1/types_alibabaprovider.go
  vendor/github.com/openshift/api/machine/v1/types_aws.go
  vendor/github.com/openshift/api/machine/v1/types_awsplacementgroup.go
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/types_powervsprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_vsphereprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#55 Implement finalizer addition
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/controllers/controlplanemachineset/status.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go
  pkg/test/resourcebuilder/openshift_machine_v1beta1_template.go
Labels: approved, lgtm, size/M

#57 Add ownerrefs to machines owned by CPMS
  .gitignore
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
Labels: approved, lgtm, size/L

#60 [OCPCLOUD-1622] Ensure zone from providerSpec matches control plane machines
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
Labels: approved, lgtm, size/M

#64 Move ConvertAWSResourceReference test
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/aws_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
Labels: approved, lgtm, size/L

#65 Allow the operator to update a ControlPlaneMachineSet status subresource
  manifests/0000_31_control-plane-machine-set-operator_01_rbac.yaml
Labels: approved, lgtm, size/XS

#66 [OCPCLOUD-1556] Implement provider config abstraction for GCP
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/gcp.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/gcp_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
Labels: approved, lgtm, size/L

#61 [OCPCLOUD-1486] ControlPlaneMachineSet deletion logic
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/machineproviders/providers/machineproviders.go
  pkg/test/resourcebuilder/consts.go
  pkg/test/resourcebuilder/control_plane_machine_set.go
  pkg/test/resourcebuilder/machine.go
  pkg/test/resourcebuilder/openshift_machine_v1beta1_template.go
Labels: approved, lgtm, size/L

#68 controller: validateClusterState add behaviour details
  pkg/controllers/controlplanemachineset/controller.go
Labels: approved, lgtm, size/XS

#56 [OCPCLOUD-1502] RollingUpdate Strategy
  pkg/controllers/controlplanemachineset/updates.go
  pkg/controllers/controlplanemachineset/updates_test.go
Labels: approved, lgtm, size/XL

#70 Remove redundant "template" in error path
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
Labels: approved, lgtm, size/XS
