Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2023-06, with the labels that each got.

#200 [CORS-2666] Add Nutanix support for CPMSO
  pkg/controllers/controlplanemachinesetgenerator/controller.go
  pkg/controllers/controlplanemachinesetgenerator/controller_test.go
  pkg/controllers/controlplanemachinesetgenerator/nutanix.go
  pkg/controllers/controlplanemachinesetgenerator/utils.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/nutanix.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go
  test/e2e/framework/framework.go
Labels: approved, lgtm, size/XL, jira/valid-bug

#180 OCPCLOUD-2016: Surface cpms vs machine diff
  pkg/controllers/controlplanemachineset/updates.go
  pkg/controllers/controlplanemachineset/updates_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
  pkg/machineproviders/types.go
  pkg/test/resourcebuilder/machineproviders/machine_info.go
Labels: approved, lgtm, qe-approved, size/XL, jira/valid-reference

#201 docs: Off-by-one error
  docs/user/installation.md
Labels: approved, lgtm, size/M

#221 OCPBUGS-15308: Fix lint issue
  pkg/controllers/controlplanemachineset/updates_test.go
Labels: approved, lgtm, size/S, jira/valid-bug, jira/valid-reference

#219 [release-4.12] OCPBUGS-15198: Surface cpms vs machines diff
  pkg/controllers/controlplanemachineset/updates.go
  pkg/controllers/controlplanemachineset/updates_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
  pkg/machineproviders/types.go
  pkg/test/resourcebuilder/machine_info.go
Labels: approved, lgtm, cherry-pick-approved, size/XL, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#220 OCPBUGS-15338: Fix flaking machine mapping testing
  go.mod
  go.sum
  pkg/controllers/controlplanemachineset/updates.go
  pkg/controllers/controlplanemachineset/updates_test.go
  pkg/machineproviders/mock/zz_generated_machine_provider_mock.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
  pkg/machineproviders/types.go
  vendor/github.com/openshift/api/machine/v1alpha1/doc.go
  vendor/github.com/openshift/api/machine/v1alpha1/register.go
  vendor/github.com/openshift/api/machine/v1alpha1/types_openstack.go
  vendor/github.com/openshift/api/machine/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/Makefile
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/config/v1/infrastructure.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/openstack_failure_domains.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/machine.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/openstack_provider_spec.go
  vendor/k8s.io/klog/v2/format.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, jira/valid-bug, jira/valid-reference
