Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2023-07, with the labels that each got.

#195 OSASINFRA-3133 - OpenStack support
  docs/user/README.md
  docs/user/failure-domains.md
  docs/user/installation.md
  go.mod
  go.sum
  pkg/controllers/controlplanemachinesetgenerator/aws.go
  pkg/controllers/controlplanemachinesetgenerator/azure.go
  pkg/controllers/controlplanemachinesetgenerator/controller.go
  pkg/controllers/controlplanemachinesetgenerator/controller_test.go
  pkg/controllers/controlplanemachinesetgenerator/gcp.go
  pkg/controllers/controlplanemachinesetgenerator/openstack.go
  pkg/controllers/controlplanemachinesetgenerator/utils.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/openstack.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/openstack_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
  test/e2e/framework/framework.go
  test/e2e/helpers/controlplanemachineset.go
  test/e2e/helpers/machine.go
  test/e2e/presubmit_test.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/awsdnsspec.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/dnsplatformspec.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/dnsspec.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/machine/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/machine/applyconfigurations/machine/v1/failuredomains.go
  vendor/github.com/openshift/client-go/machine/applyconfigurations/machine/v1/openstackfailuredomain.go
  vendor/github.com/openshift/client-go/machine/applyconfigurations/machine/v1/rootvolume.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#217 OSASINFRA-3180: openstack: volume type in failure domain
  docs/user/failure-domains.md
  docs/user/installation.md
  go.mod
  go.sum
  pkg/controllers/controlplanemachinesetgenerator/controller_test.go
  pkg/controllers/controlplanemachinesetgenerator/openstack.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/openstack.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/openstack_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/openstack_failure_domains.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/openstack_provider_spec.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, jira/valid-reference

#224 e2e: OpenStack CPMS created automatically
  test/e2e/framework/framework.go
Labels: approved, lgtm, size/XS

#226 vendoring: update openshift/api
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/stable.dns.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.dns.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/stable.controlplanemachineset.openstack.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#227 manifests: Shift from run level 31 to 30
  hack/crds-sync.sh
  manifests/0000_30_control-plane-machine-set-operator_00_controlplanemachineset.crd.yaml
  manifests/0000_30_control-plane-machine-set-operator_01_rbac.yaml
  manifests/0000_30_control-plane-machine-set-operator_02_service.yaml
  manifests/0000_30_control-plane-machine-set-operator_03_deployment.yaml
  manifests/0000_30_control-plane-machine-set-operator_04_clusteroperator.yaml
  manifests/0000_30_control-plane-machine-set-operator_05_webhook.yaml
Labels: approved, lgtm, size/XS
