Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2023-02, with the labels that each got.

#165 OCPBUGS-6760: webhooks: disable mandatory TargetPools validation on GCP
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
Labels: approved, lgtm, size/S, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#168 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#170 e2e: periodics: remove test with cluster-wide-proxy
  test/e2e/helpers/proxy.go
  test/e2e/periodic_test.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/apps/v1/daemonset.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
