Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2023-08, with the labels that each got.

#231 openstack: volumeType is now required
  go.mod
  go.sum
  manifests/0000_30_control-plane-machine-set-operator_00_controlplanemachineset.crd.yaml
  pkg/controllers/controlplanemachinesetgenerator/controller_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/openstack_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/custom.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1alpha1/0000_10_config-operator_01_backup-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1alpha1/register.go
  vendor/github.com/openshift/api/config/v1alpha1/techpreview.backup.testsuite.yaml
  vendor/github.com/openshift/api/config/v1alpha1/types_backup.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/stable.controlplanemachineset.openstack.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/cloudcontrollermanagerstatus.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/externalplatformstatus.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/gcpplatformstatus.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/gcpresourcelabel.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/gcpresourcetag.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/config/v1/platformstatus.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/machine/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/machine/applyconfigurations/machine/v1/rootvolume.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/openstack_failure_domains.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#232 test/e2e: override `RootVolume.VolumeType` to ""
  test/e2e/framework/framework.go
Labels: approved, lgtm, size/XS

#229 OCPCLOUD-2130: Add subnet to Azure FD, fix for optional fields in FD
  docs/user/failure-domains.md
  docs/user/installation.md
  go.mod
  go.sum
  manifests/0000_30_control-plane-machine-set-operator_00_controlplanemachineset.crd.yaml
  pkg/controllers/controlplanemachinesetgenerator/azure.go
  pkg/controllers/controlplanemachinesetgenerator/controller_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/aws.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/azure.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/azure_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/gcp.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/stable.clusterversion.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/azure_failure_domains.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/azure_provider_spec.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, jira/valid-reference

#233 Revert "OCPCLOUD-2130: Add subnet to Azure FD, fix for optional fields in FD"
  docs/user/failure-domains.md
  docs/user/installation.md
  go.mod
  go.sum
  manifests/0000_30_control-plane-machine-set-operator_00_controlplanemachineset.crd.yaml
  pkg/controllers/controlplanemachinesetgenerator/azure.go
  pkg/controllers/controlplanemachinesetgenerator/controller_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/aws.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/azure.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/azure_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/gcp.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/stable.clusterversion.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/azure_failure_domains.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/azure_provider_spec.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, jira/valid-reference

#230 OCPBUGS-18013: Enhance wehbooks to dry run machine creation to validate provider spec
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
Labels: approved, lgtm, size/M, jira/valid-bug, jira/valid-reference
