Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2023-10, with the labels that each got.

#244 OCPBUGS-20070: fix: e2e: add gcp custom type to test framework
  test/e2e/framework/framework.go
  test/e2e/framework/framework_test.go
Labels: approved, lgtm, size/L, jira/severity-low, jira/valid-bug, jira/valid-reference

#246 OCPBUGS-20070: e2e: gcp e2-custom increase memory
  test/e2e/framework/framework.go
  test/e2e/framework/framework_test.go
Labels: approved, lgtm, size/M, jira/severity-low, jira/valid-bug, jira/valid-reference

#247 [release-4.14] OCPBUGS-20408: fix: e2e: add gcp custom type to test framework
  test/e2e/framework/framework.go
  test/e2e/framework/framework_test.go
Labels: approved, lgtm, size/L, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#252 OCPBUGS-21863: webhooks: set min version TLS 1.2
  cmd/control-plane-machine-set-operator/main.go
  pkg/util/tls.go
Labels: approved, lgtm, size/M, jira/valid-bug, jira/valid-reference

#253 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#250 SPLAT-1211: recognize topology and failure domains represented by the infrastructure resource
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/suite_test.go
  pkg/controllers/controlplanemachinesetgenerator/aws.go
  pkg/controllers/controlplanemachinesetgenerator/azure.go
  pkg/controllers/controlplanemachinesetgenerator/controller.go
  pkg/controllers/controlplanemachinesetgenerator/controller_test.go
  pkg/controllers/controlplanemachinesetgenerator/gcp.go
  pkg/controllers/controlplanemachinesetgenerator/nutanix.go
  pkg/controllers/controlplanemachinesetgenerator/openstack.go
  pkg/controllers/controlplanemachinesetgenerator/utils.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/suite_test.go
  pkg/machineproviders/providers/suite_test.go
  pkg/test/suite_test.go
  pkg/util/infrastructure.go
  pkg/util/watch_filters.go
  pkg/webhooks/controlplanemachineset/suite_test.go
  pkg/webhooks/controlplanemachineset/webhooks.go
  test/e2e/framework/framework.go
Labels: approved, lgtm, size/L, jira/valid-reference
