Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2023-04, with the labels that each got.

#182 OCPBUGS-11142: controlplanemachineset: start watching control plane nodes
  cmd/control-plane-machine-set-operator/main.go
  hack/test.sh
  pkg/controllers/controlplanemachineset/controller.go
  pkg/util/suite_test.go
  pkg/util/watch_filters.go
  pkg/util/watch_filters_test.go
Labels: approved, lgtm, bugzilla/valid-bug, size/L, jira/valid-bug, jira/valid-reference

#175 OCPBUGS-2960: Check ProviderSpec before generating MachineInfo
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
  test/e2e/framework/framework.go
  test/e2e/helpers/controlplanemachineset.go
  test/e2e/presubmit_test.go
Labels: approved, lgtm, bugzilla/valid-bug, size/L, jira/valid-bug, jira/valid-reference

#185 OCPBUGS-11389: Use PlatformStatus instead of PlatformSpec to determine platform
  pkg/controllers/controlplanemachinesetgenerator/controller.go
Labels: approved, lgtm, bugzilla/valid-bug, size/XS, jira/valid-bug, jira/valid-reference

#191 Inject a failure domain into a dry-run created machine
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
Labels: approved, lgtm, size/M

#193 [release-4.12] OCPBUGS-8503: machine's node must be ready for CPMS machine to be ready + fixes
  cmd/control-plane-machine-set-operator/main.go
  hack/test.sh
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/controllers/controlplanemachineset/updates.go
  pkg/controllers/controlplanemachineset/updates_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
  pkg/test/resourcebuilder/node.go
  pkg/util/suite_test.go
  pkg/util/watch_filters.go
  pkg/util/watch_filters_test.go
  test/integration/machine_manager.go
Labels: approved, lgtm, bugzilla/valid-bug, size/XXL, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#196 OCPBUGS-7921: Prioritise machine mapping over alphabetical mapping
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, size/L, jira/severity-low, jira/valid-bug, jira/valid-reference

#199 OCPBUGS-12240: Run `make crds-sync`
  manifests/0000_31_control-plane-machine-set-operator_00_controlplanemachineset.crd.yaml
Labels: approved, lgtm, bugzilla/valid-bug, size/XXL, jira/severity-low, jira/valid-bug, jira/valid-reference

#204 [release-4.12] OCPBUGS-12440: Prioritise machine mapping over alphabetical mapping
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
Labels: approved, lgtm, bugzilla/valid-bug, size/L, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference
