Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2024-06, with the labels that each got.

#294 OCPBUGS-20061: Add unreadyNodeGracePeriod for allowing brief node hiccups
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
Labels: approved, lgtm, size/L, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#297 OCPBUGS-35069: Improved debugging of API listing errors
  test/e2e/framework/utils.go
  test/e2e/helpers/machine.go
Labels: approved, lgtm, size/S, jira/valid-bug, jira/valid-reference

#303 [release-4.14] OCPBUGS-35338: Improved debugging of API listing errors
  test/e2e/framework/utils.go
  test/e2e/helpers/machine.go
Labels: approved, lgtm, size/S, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#305 OCPBUGS-35416: Wait for ControlPlaneMachineSet to be created when waiting for it to be updated
  test/e2e/helpers/controlplanemachineset.go
Labels: approved, lgtm, size/XS, jira/valid-bug, jira/valid-reference

#310 NO-JIRA: CPMS Cluster Operator should set related objects
  pkg/controllers/controlplanemachineset/cluster_operator.go
  pkg/controllers/controlplanemachineset/cluster_operator_test.go
Labels: approved, lgtm, size/L, jira/valid-reference

#311 NO-JIRA: Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS, jira/valid-reference
