Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2024-05, with the labels that each got.

#292 Drop CRDs for CPMS
  Makefile
  hack/crds-sync.sh
  manifests/0000_30_control-plane-machine-set-operator_00_controlplanemachineset-customnoupgrade.crd.yaml
  manifests/0000_30_control-plane-machine-set-operator_00_controlplanemachineset-default.crd.yaml
  manifests/0000_30_control-plane-machine-set-operator_00_controlplanemachineset-techpreviewnoupgrade.crd.yaml
Labels: do-not-merge/hold, size/XXL

#282 AUTH-482: set required-scc for openshift workloads
  manifests/0000_30_control-plane-machine-set-operator_03_deployment.yaml
Labels: approved, lgtm, size/XS, jira/valid-reference

#291 OCPBUGS-32947: Modified webhook to reject changes to vsphere fields coming from failure domains.
  pkg/webhooks/controlplanemachineset/suite_test.go
  pkg/webhooks/controlplanemachineset/webhooks.go
  pkg/webhooks/controlplanemachineset/webhooks_test.go
Labels: approved, lgtm, size/L, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
