Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2024-02, with the labels that each got.

#274 OCPBUGS-28230: add FallbackToLogsOnError for easier debugging
  manifests/0000_30_control-plane-machine-set-operator_03_deployment.yaml
Labels: approved, lgtm, size/XS, jira/valid-bug, jira/valid-reference

#276 OCPBUGS-29114: Fixed control plane machine set handling of static IPs when AddressesFromPools is not in use.
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/vsphere.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/vsphere_test.go
Labels: approved, lgtm, size/M, jira/severity-important, jira/valid-bug, jira/valid-reference

#278 OCPBUGS-29249: Never delete a Machine when there's a single Machine in an index
  pkg/controllers/controlplanemachineset/updates.go
  pkg/controllers/controlplanemachineset/updates_test.go
Labels: approved, lgtm, size/M, jira/valid-bug, jira/valid-reference

#273 SPLAT-1410: Modified vSphere config provider to not lose AddressesFromPools when applying Failure Domains
  go.mod
  go.sum
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/vsphere.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/vsphere_test.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/vsphere_provider_spec.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, jira/valid-reference, acknowledge-critical-fixes-only
