Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2025-01, with the labels that each got.

#332 OAPE-19: Support customized control plane machine names with prefix
  cmd/control-plane-machine-set-operator/main.go
  pkg/controllers/controlplanemachineset/controller.go
  pkg/controllers/controlplanemachineset/controller_test.go
  pkg/controllers/controlplanemachineset/suite_test.go
  pkg/controllers/controlplanemachinesetgenerator/controller_test.go
  pkg/machineproviders/providers/machineproviders.go
  pkg/machineproviders/providers/machineproviders_test.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
  pkg/util/feature_gate.go
  test/e2e/helpers/controlplanemachineset.go
  test/e2e/helpers/feature_gate.go
  test/e2e/helpers/machine.go
  test/e2e/presubmit_test.go
Labels: approved, lgtm, size/XXL, jira/valid-reference

#338 OAPE-78: Add e2e periodic job for machine name prefix
  test/e2e/periodic_test.go
Labels: approved, lgtm, size/M, jira/valid-reference, acknowledge-critical-fixes-only

#342 [release-4.13] OCPBUGS-48259: Add unreadyNodeGracePeriod for allowing brief node hiccups
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
Labels: approved, lgtm, size/L, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#344 [release-4.12] OCPBUGS-48325: Add unreadyNodeGracePeriod for allowing brief node hiccups
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
  pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
Labels: approved, lgtm, size/L, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#339 NO-JIRA: Update support matrix
  docs/user/README.md
  pkg/controllers/controlplanemachinesetgenerator/controller.go
Labels: approved, lgtm, size/S, jira/valid-reference, acknowledge-critical-fixes-only

#335 SPLAT-1817: Bump openshift/api to get vSphere multi disk support
  go.mod
  go.sum
  pkg/controllers/controlplanemachineset/cluster_operator.go
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machine/v1beta1/types_vsphereprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: approved, lgtm, size/S, jira/valid-reference, acknowledge-critical-fixes-only
