Repository openshift/cluster-control-plane-machine-set-operator, pull requests merged in 2025-03, with the labels that each got.

#351 OAPE-126: Include CPMSMachineNamePrefix feature-gate name in e2e tests
  test/e2e/periodic_test.go
  test/e2e/presubmit_test.go
Labels: approved, lgtm, size/XS, jira/valid-reference

#352 OCPBUGS-52224: Bump to golang.org/x/oauth2@v0.27.0
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/modules.txt
Labels: approved, lgtm, size/XS, jira/severity-important, jira/valid-bug, jira/valid-reference

#353 OAPE-147: Add E2E tests for MachineNamePrefix with OnDelete update strategy
  test/e2e/periodic_test.go
  test/e2e/presubmit_test.go
Labels: approved, lgtm, size/M, jira/valid-reference
